### ISSUE TITLE
Need to fix the map

### ISSUE THREAD

**Issue by lmclister** [lmclister/testtwf-shanghai-issues#1]
currently has the wrong location and is not rendering properly.

**Comment by zerlot** [comment]
I have sent you a email, changed the map to google. please check.

**Comment by zerlot** [comment]
About the map, you can change it to google map:
http://ditu.google.cn/maps?q=%E4%B8%8A%E6%B5%B7%E6%B5%A6%E4%B8%9C%E7%A2%A7%E6%B3%A2%E8%B7%AF%E5%8D%9A%E9%9B%85%E9%85%92%E5%BA%97&hl=zh-CN&ie=UTF8&sll=39.90403,116.407526&sspn=0.868059,2.04895&oq=%E4%B8%8A%E6%B5%B7%E6%B5%A6%E4%B8%9C%E5%8D%9A%E9%9B%85&brcurrent=3,0x35b277c0c6f38231:0x27b7e58bc9f76994,0,0x35ad8c73cd3952c7:0xbb190e9364c4e592%3B5,0,0&hq=%E5%8D%9A%E9%9B%85%E9%85%92%E5%BA%97&hnear=%E4%B8%8A%E6%B5%B7%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E7%A2%A7%E6%B3%A2%E8%B7%AF&t=m&z=17
or
https://maps.google.com/maps?q=%E4%B8%AD%E5%9B%BD%E4%B8%8A%E6%B5%B7%E6%B5%A6%E4%B8%9C%E7%A2%A7%E6%B3%A2%E8%B7%AF%E5%8D%9A%E9%9B%85%E9%85%92%E5%BA%97&hl=zh-CN&ie=UTF8&sll=37.0625,-95.677068&sspn=56.200193,131.132813&oq=%E4%B8%8A%E6%B5%B7%E6%B5%A6%E4%B8%9C%E5%8D%9A%E9%9B%85&hq=%E5%8D%9A%E9%9B%85%E9%85%92%E5%BA%97&hnear=%E4%B8%AD%E5%9B%BD%E4%B8%8A%E6%B5%B7%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E7%A2%A7%E6%B3%A2%E8%B7%AF&t=m&z=17

**Comment by lmclister** [comment]
used g maps. fixed
commit https://github.com/adobe-webplatform/testthewebfwd/commit/f09a316c3e02ec28e91dc520d444c8812f95f505
