### ISSUE TITLE
Need the list of specifications and links to the specifications so that they can be added under the requirements section

### ISSUE THREAD

**Issue by lmclister** [lmclister/testtwf-shanghai-issues#16]
also, not sure if there is anything else that you would like to include in that section.  If there is something, please add it to this issue

**Comment by zerlot** [comment]
I already sent email to ask Baidu to help us collect this part of content, they will do it asap.

**Comment by zerlot** [comment]
## I got this part content:

要求(requirement)
  可熟练使用HTML, JavaScript和CSS编程。本次活动请自带笔记本。
  编程环境搭建
  选择一款你喜欢的文本编辑器或IDE。
  安装各主流浏览器(如Firefox、Chrome、Opera等)。
  从https://github.com/w3c/testharness.js 下载测试相关的库文件。
  准备一个FTP客户端（如FileZilla）并熟悉其使用。
  如果你有问题，我们有专家会帮助你。

  在参与活动前你需要阅读和熟悉以下至少一个功能，这样会让你有些基础。以下是我们将着重学习和测试的web功能:
·         HTML5 File API：http://www.w3.org/TR/FileAPI/
·         HTML5 Drag and Drop：http://www.w3.org/TR/html5/editing.html#dnd
·         HTML5 WebStorage：http://www.w3.org/TR/webstorage/
·         CSS3 Transforms：http://www.w3.org/TR/css3-transforms/
·         CSS3 Grid Layout: http://www.w3.org/TR/css3-grid-layout/
·         CSS3 Background and Borders:http://www.w3.org/TR/css3-background/
如果你想编写或修改测试，我们非常乐意帮忙。

**Comment by lmclister** [comment]
added and closing
Commit: https://github.com/adobe-webplatform/testthewebfwd/commit/baeafa746ed9b785baaa9a0d3e4c125ba7915b0b
