### ISSUE TITLE
Add New experts that Zerlot provides

### ISSUE THREAD

**Issue by lmclister** [lmclister/testtwf-shanghai-issues#17]

**Comment by zerlot** [comment]
## New Featured Experts (update.1)

贺师骏
![heshijun_baixing](https://f.cloud.github.com/assets/1031783/853087/73a0c284-f4cb-11e2-8f1a-4db2a576ea1b.jpg)
百姓网，开发工程师

张云龙
![zhangyunlong_mozila](https://f.cloud.github.com/assets/1031783/853107/0b0d63b6-f4cc-11e2-95ec-ce5982c02eb4.jpg)
Mozilla，资深工程师

陆华
![luhua_alibaba](https://f.cloud.github.com/assets/1031783/853095/c8eddf92-f4cb-11e2-9095-ff25b94320af.jpg)
支付宝，资深前端开发工程师

施丹侠
![shidanxia_alibaba](https://f.cloud.github.com/assets/1031783/853103/e9a0493c-f4cb-11e2-93d3-07b29ee87dfb.jpg)
支付宝，资深前端开发工程师

缪传杰
![miaochuanjie_huawei](https://f.cloud.github.com/assets/1031783/853109/2ef7a1b0-f4cc-11e2-87a0-d91b476f273e.jpg)
华为，资深开发工程师

赵锦江
![zhaojinjiang_maxthon](https://f.cloud.github.com/assets/1031783/853113/553be02a-f4cc-11e2-861c-660f59417bbc.png)
遨游，资深工程师

**Comment by lmclister** [comment]
For future additions to the experts section, please name the images and post them somewhere or email me a zip.  Having a hard time sorting these out :)

**Comment by lmclister** [comment]
added and live.  closing
commit:
https://github.com/adobe-webplatform/testthewebfwd/commit/7cb49b3ea0a24db77b66ef286bb623f2e225a7f8

**Comment by zerlot** [comment]
## New Featured Experts (update.2）

李杰
![lijie_alibaba](https://f.cloud.github.com/assets/1031783/869626/332a8366-f809-11e2-84c3-00ed4cc1b036.jpg)
阿里巴巴，前端工程师

张荣
![zhangrong_uc](https://f.cloud.github.com/assets/1031783/869629/509f31d0-f809-11e2-85a8-cd4ada68e39b.jpg)
UCWEB，前端工程师

李海翔
![lihaixiang_uc](https://f.cloud.github.com/assets/1031783/869630/6f2feca2-f809-11e2-80c6-65f4e96dfcbe.jpg)
UCWEB，前端工程师

Please Check email for zipped photos.

**Comment by lmclister** [comment]
added, closing
commits
https://github.com/adobe-webplatform/testthewebfwd/commit/5cd95e8d5ca0649907b4e0a402453e5d4b6b41c0
https://github.com/adobe-webplatform/testthewebfwd/commit/2436b5bc64c2b03e13abe331bd3999b25d98b7e1
