### ISSUE TITLE
Need links to the W3C account request forma and the grant of license is the requirements section

### ISSUE THREAD

**Issue by lmclister** [lmclister/testtwf-shanghai-issues#18]
http://www.w3.org/Help/Account/Request/Public 
http://www.w3.org/2002/09/wbs/1/testgrants2-200409

**Comment by zerlot** [comment]
Add the following text in requirement section.

W3C 公共帐户申请表： http://www.w3.org/Help/Account/Request/Public 
测试用例公共授权许可：http://www.w3.org/2002/09/wbs/1/testgrants2-200409

**Comment by lmclister** [comment]
closing
commit https://github.com/adobe-webplatform/testthewebfwd/commit/ced7960cb99230fab2cddff25956f5555379ab99
