### ISSUE TITLE
Need an updated & translated github setup doc

### ISSUE THREAD

**Issue by lmclister** [lmclister/testtwf-shanghai-issues#19]
original is at http://testthewebforward.org/resources/github_test_submission.html

I will update, then notify that it needs translation

**Comment by lmclister** [comment]
we will also need translated text for the link on the Shanghai page
"Setup Github"

**Comment by zerlot** [comment]
I think those developers can totally understand the github setup instructions well. Most of them are reading English docs when they are working.

**Comment by lmclister** [comment]
ok, well I'll get the EN doc updated at the least

**Comment by lmclister** [comment]
working on the PR for the main testtwf repo...
