### ISSUE TITLE
Need replace some companies name in "Test the web forward介绍"

### ISSUE THREAD

**Issue by zerlot** [lmclister/testtwf-shanghai-issues#22]
Replace this word

"Adobe联合来自W3C、百度、谷歌、Mozilla、欧朋、Intel、腾讯、360、傲游、UC、华为、淘宝等等的技术专家现场帮助开发者解决活动中遇到的难题。"

to

"W3C、百度和Adobe联合Intel、阿里巴巴、傲游、UC、华为、支付宝、百姓网、Mozilla及社区的技术专家现场帮助开发者解决活动中遇到的难题。"

in the paragraph of "Test the web forward介绍".

**Comment by lmclister** [comment]
fixed.  Please verify.

Commit: https://github.com/adobe-webplatform/testthewebfwd/commit/4e2a97c606a10b3e30a9a26e7915cd6501ee39cd
