### ISSUE TITLE
some minor changes(updates) for typos and missing infos

### ISSUE THREAD

**Issue by zerlot** [lmclister/testtwf-shanghai-issues#25]
The followings are some changes we found in the page, they are some typos and missing words need to be updated.

Replace the content in the "Test The Web Forward介绍" section

"Test the Web Forward活动的意图是让关注web标准的开发者直接参与到web平台的贡献中去。W3C、百度和Adobe联合Intel、阿里巴巴、傲游、UC、华为、支付宝、百姓网、Mozilla及社区的技术专家现场帮助开发者解决活动中遇到的难题。在这次hack活动中，你会了解最新的HTML5功能规范，并学习如何编写对应的测试用例，这些测试用例会帮助更多浏览器更一致地实现这些功能。现场会有众多专家会帮助你完成HTML5相关规范的测试用例编写工作，并指导你如何提交错误报告。你会通过编程实战学习到全新的技术知识，这些会对你未来的项目设计开发和自身的技术水平提升有很大的帮助。

我们将为CSS规范编写测试，这将有助于测试浏览器对这些标准的实现，并在它们表现不一致时提交错误报告。我们还将听到专家们对这些标准的意见以及浏览器如何实施这些标准的信息。"

To

"Test the Web Forward活动的意图是让关注Web标准的开发者直接参与到Web平台的贡献中去。百度联合来自W3C、Adobe、Mozilla、阿里、金山、UC、华为、傲游、百姓网等的技术专家，现场帮助开发者解决活动中遇到的难题。在这次Hack活动中，你会了解最新的HTML5和CSS3功能规范，并学习如何编写对应的测试用例，这些测试用例会帮助更多浏览器更一致地实现这些功能。现场会有众多专家会帮助你完成HTML5和CSS3相关规范的测试用例编写工作，并指导你如何提交错误报告。你会通过编程实战学习到全新的技术知识，这些会对你未来的项目设计开发和自身的技术水平提升有很大的帮助。

我们将为HTML5和CSS3多个规范编写测试，这将有助于测试浏览器对这些标准的实现，并在它们表现不一致时提交错误报告。我们还将听到专家们对这些标准的意见以及浏览器如何实施这些标准的信息。"

other minor changes are following:
1. Change "李杰" to "李杰（一丝）"
2. Change "贺师骏" to "贺师俊"
3. Change expert "张荣"s title from "UCWEB,前端工程师" to "UCWEB,高级QA工程师"
4. Change expert "李海翔"s title from "UCWEB,前端工程师" to "UCWEB,开发工程师"

**Comment by lmclister** [comment]
done
commit: https://github.com/adobe-webplatform/testthewebfwd/commit/e8b172df4b79a000b23bbfe9007a668afcb85d4f
