### ISSUE TITLE
Schedule: unclear what is happening between 5:30pm and 6:30pm on day 1

### ISSUE THREAD

**Issue by lmclister** [lmclister/testtwf-shanghai-issues#6]

**Comment by zerlot** [comment]
I will check with W3C and Baidu. please stay tuned.

**Comment by lmclister** [comment]
there is also a gap between 6:10 and 6:30.

**Comment by zerlot** [comment]
## Agenda Update on 7.20

8月17日
1:30pm ~ 2:00pm 报到
2:00pm ~ 2:15pm 欢迎&介绍 (百度VP, 郑子斌)
2:15pm ~ 3:00pm HTML5技术最新进展 (W3C HTML联合主席, Paul Cotton)
3:00pm ~ 3:15pm 演讲Web App 国内发展机遇 (创新谷合伙人, 许洪波)
3:15pm ~ 3:30pm 茶歇
3:30pm ~ 3:50pm 快速讲解与演示：HTML5 File API
3:50pm ~ 4:10pm 快速讲解与演示：HTML5 Drag and Drop API
4:10pm ~ 4:30pm 快速讲解与演示：HTML5 Web Storage
4:30pm ~ 4:45pm 快速讲解：CSS Transforms, Grid Layout, Backgrounds and Borders
4:45pm ~ 5:15pm 标准测试用例编写及提交流程演示
5:15pm ~ 5:45pm 答疑与分组
5:45pm ~ 6:00pm 奖项介绍
6:00pm 晚餐

8月18日 
9:30 am ~ 10:00am 报到
10:00am ~ 10:20pm 热身：如何写一个好的测试用例 、如何报Bug
10:20am ~ 12:00pm Hack
12:00pm ~ 1:00 pm 午餐
1:00 pm ~ 3:00 pm Hack
3:00 pm ~ 3:30 pm 休息茶歇
3:30 pm ~ 5:30 pm Hack
5:30 pm ~ 6:00 pm 演示/奖品

**Comment by lmclister** [comment]
updates made...  closing

commit https://github.com/adobe-webplatform/testthewebfwd/commit/8ca9a670211c2ddda1094c4ea66b7594b6651d85
